### ISSUE TITLE
Installation error in hyprload.

### ISSUE THREAD

**Issue by niksingh710** [micha4w/Hypr-DarkWindow#1]
Installation throws an error in hyprload.

**Comment by micha4w** [comment]
Check out [the hyprland wiki](https://wiki.hyprland.org/Plugins/Using-Plugins/#compiling-official-plugins) for how to install a plugin. If that doesn't work, please share your steps and errors.

**Comment by micha4w** [comment]
Just realised I haven't updated my Hyprland to 0.31.0... I'll check it out!

**Comment by micha4w** [comment]
Turns out v0.31.0 wasn't the problem, but the latest git version is incompatible with v0.31.0. So if you use hyprland-git, you should be fine now, but if you use v0.31.0 you'll have to do:

In hyprland.toml, use v0.31.0:
```toml
# .config/hyprland/hyprload.toml
plugins = [
  { git = "https://github.com/micha4w/Hypr-DarkWindow", rev = "tags/v0.31.0", name = "Hypr-DarkWindow" },
 ]
```

Please try it out and if no work, share hyprland and hyprload commit refs being used.

**Comment by niksingh710** [comment]
I am on git version of Hyprland
```bash
Hyprland, built from branch main at commit 062f749450da9d280f85d3052d7f8bc9b70db62b dirty (xdg: send unconstrain events after a popup reposition (3716)).
Tag: v0.31.0-67-g062f7494

flags: (if any)
debug

```
and just reinstalled hyprload again.
Now no errors pop but hyprload not even installing the plugin.

**Comment by micha4w** [comment]
Probably be a hyprload issue then. Idk if you have any experiences with hyprload, but its weird sometimes. It will only actually install the plugin when you do `hyprctl disptach hyprload update`.

To make that this is the problem, check if the plugin built successfully:
```sh
file ~/.local/share/hyprload/plugins/src/Hypr-DarkWindow/out/hypr-darkwindow.so
```

If the file exists. It was hyprloads fault, you'll need to either run hyprload update, or install the file manually:
```sh
cp ~/.local/share/hyprload/plugins/src/Hypr-DarkWindow/out/hypr-darkwindow.so ~/.local/share/hyprload/plugins/bin/Hypr-DarkWindow.so
```
Then reloading hyprload with something like `hyprctl dispatch hyprload reload` or exiting hyprland and relogging in should make it load the plugin.

**Comment by niksingh710** [comment]
![image](https://github.com/micha4w/Hypr-DarkWindow/assets/60490474/707a39ec-8476-4a67-870e-aabf7fa7ece9)
I get this if i try to update.
and there is no `hypr-darkwindow.so`

**Comment by micha4w** [comment]
Looks like I did a stupid and didn't check whether the git push succeeded :sweat_smile:.
For me i had to go into `~/.local/share/hyprload/plugins/src/Hypr-DarkWindow` and run  a `git pull`. Then it should work, finally..

**Comment by niksingh710** [comment]
okay so now it installed but not getting listed in `hyprctl plugins list`
doing `hyprctl dispatch hyprload reload` states `Hypr-DarkWindow` getting loaded but it is not listed in `hyprctl plugins list` 

i guess it is an hyprload issue.
do you know any solution for this?

**Comment by niksingh710** [comment]
just checked sourcing `.so` file is not working either.

**Comment by niksingh710** [comment]
Just updated Hyprland and hyprload and it works perfectly fine now.
