### ISSUE TITLE
Plugins not working 

### ISSUE THREAD

**Issue by shadowelite-sec** [micha4w/Hypr-DarkWindow#3]
Is this plugin still working? I tried setting rules with Nemo and qBittorrent, but it's not changing to dark mode.

**Comment by micha4w** [comment]
Yep, works for me on Hyprland v0.39.1 with this line in my Config
```js
darkwindow_invert = class:nemo
```

You can test if the Plugin is installed correctly by runnning
```sh
hyprctl dispatch invertactivewindow
```

(Also Nemo uses your GTK Theme and qBittorrent probbaly your QT Theme, it might be a better idea to change those, since they are first party)

**Comment by shadowelite-sec** [comment]
> Yep, works for me on Hyprland v0.39.1 with this line in my Config
> 
> ```js
> darkwindow_invert = class:nemo
> ```
> 
> You can test if the Plugin is installed correctly by runnning
> 
> ```shell
> hyprctl dispatch invertactivewindow
> ```
> 
> (Also Nemo uses your GTK Theme and qBittorrent probbaly your QT Theme, it might be a better idea to change those, since they are first party)


https://github.com/micha4w/Hypr-DarkWindow/assets/54718375/de703f31-3ac5-4787-b54e-1849fdd431b5

am i missing something ?

**Comment by micha4w** [comment]
Weird, can you try this command:
```sh
hyprctl dispatch invertactivewindow
```

Also send Hyprland version, thanks

**Comment by shadowelite-sec** [comment]
> Weird, can you try this command:
> 
> ```shell
> hyprctl dispatch invertactivewindow
> ```
> 
> Also send Hyprland version, thanks

i tried 
`hyprctl dispatch invertactivewindow` (also with keybind)

it just returing ok 

hyprctl version 

```
Hyprland, built from branch makepkg at commit faa9017043e5471863646fdfd3b4a0404ff69d4c  (renderer: fix rounding of the size of fractionally scaled monitors (5748)).
Date: Thu Apr 25 23:22:49 2024
Tag: v0.39.1-81-gfaa90170, commits: 4541
```

**Comment by micha4w** [comment]
Ye sorry my fault, there was a breaking change in the Hyprland API, though its weird that you were even able to install the plugin, since it should have erorred while compiling...

Anyway, I adapted the code :)

**Comment by shadowelite-sec** [comment]
> Ye sorry my fault, there was a breaking change in the Hyprland API, though its weird that you were even able to install the plugin, since it should have erorred while compiling...
> 
> Anyway, I adapted the code :)

now its working, thanks :smile:
